### PR TITLE
attestation: update to latest linux-sgx branch

### PR DESCRIPTION
**Pull request by gaojiaqi7**
Closes https://github.com/intel/MigTD/issues/154

### CODE REVIEW

**Comment by jyao1** [comment]
What is the difference between original code to gen .a lib and the new code?

**Comment by jyao1** [comment]
do you need to update gitsubmodule?

**Comment by gaojiaqi7** [comment]
It has been updated in the commit

**Comment by gaojiaqi7** [comment]
> What is the difference between original code to gen .a lib and the new code?

There is no source code difference between the existing static library and the new branch.

**Review by jyao1 — APPROVED** [review]

**Pull request merged**
