### PR TITLE
vsock/virtio-serial: pop all the received packets

### PR DESCRIPTION
**Pull request by gaojiaqi7**
After receiving from vsock/virtio-serial transport layer, pop all the data packet from device and try to fill the caller's buffer as much as possible.

### CODE REVIEW

**Review by jyao1 — APPROVED** [review]

**Comment by jyao1** [comment]
please update serial as well.

**Review by liuw1 — APPROVED** [review]
LGTM

**Comment by liuw1** [comment]
Cross platform pre-migration test pass.

**Comment by jyao1** [comment]
Would you please fix the conflict?

**Pull request closed without merging**
